### ISSUE TITLE
Style Consistency for Block Content

### ISSUE THREAD

**Issue by ozgurcoban** [ozgurcoban/digital-studio#3]
Ensure that all styles within block content are consistent with the theme from shadcn, including elements like bold text. Update styles to improve readability and appearance, especially for dark mode compatibility, ensuring the content seamlessly integrates with the overall theme.

https://ozbyte.se/posts/azen

![Image](https://github.com/user-attachments/assets/454259bb-e500-4dd8-b8e4-456bd41d9bd9)
![Image](https://github.com/user-attachments/assets/925679d5-57ea-4d0c-b614-f4173a949e04)

**Comment by MARSIF123** [comment]
To ensure all styles in the block content align with the shadcn theme and improve readability for dark mode, we need to customize the portable text component. For instance, we can add:

`bold: ({ value }: { value: any }) => {`
`  return <strong className="font-bold dark:text-white">{value}</strong>;`
`},`

This will help maintain consistent styling across all text elements, enhancing their integration with the overall theme.

**Comment by MARSIF123** [comment]
The link text color wasn’t visible in dark mode, so I added the following example colors in global.css:

`--link: 210, 50%, 50%; /* Example color for light mode (HSL) */`
`--link-hover: 210, 70%, 40%; /* Example hover color for light mode (HSL) */`

You can adjust these values according to your theme. Additionally, you’ll need to use the `text-link` and `hover:text-link-hover` classes whenever the link component is used. The configuration for these classes has been added to the Tailwind config file.

Other elements like headings, paragraphs, and bullet points can also be customized there. Feel free to tweak the code to style the blog content as you like.

**Comment by ozgurcoban** [comment]
I updated the code and moved the strong component into the marks property:

```
marks: {
  strong: ({ children }: { children: React.ReactNode }) => {
    return (
      <strong className="font-bold text-secondary-foreground">
        {children}
      </strong>
    );
  },
},
```
