### ISSUE TITLE
Request feedback on TypeScript implementation

### ISSUE THREAD

**Issue by ozgurcoban** [ozgurcoban/digital-studio#4]
I'm learning TypeScript and would appreciate feedback on my implementation. Specifically, I'd like to know if the way I've imported Slug and defined HeaderProps is correct or if it can be improved. It doesn't feel quite right to me, so any guidance would be helpful.

The file is @/components/Blog/BlogHeader.tsx

![Image](https://github.com/user-attachments/assets/658c207f-1583-4fa7-a378-78242af5c18e)

**Comment by MARSIF123** [comment]
You can check the sanity.types.ts file to verify the types. Since the data comes from POST_Query, you can look for the POSTS_QUERYResult type. Also, the way you're importing Slug is correct, so no need to worry about that part.
